#!/bin/bash
gcc -g   -o vied1 server_example_goose.c static_model.c -I../../config -I../../hal/inc -I../../src/common/inc -I../../src/mms/inc -I../../src/mms/inc_private -I../../src/mms/asn1 -I../../src/iec61850/inc -I../../src/iec61850/inc_private -I../../src/goose -I../../src/sampled_values -I../../src/logging -I../../src/tls ../../build/libiec61850.a -lpthread -lm
./vied1 lo
